### PR TITLE
Dynamo db example

### PR DESCRIPTION
**Pull request by marcusoftnet**
Created a Create, Read & Delete example for some trivial data. 

There's a little bit of a setup around this; IAM access rights for the executor role and creating the table in dynamodb. The latter can be done in code but felt out-of-scope. 

Hope this can be useful. Learned a lot

### CODE REVIEW

**Comment by gojko** [comment]
Hi, before merging, I propose the following changes to make it easier for people to get started:

1) use `Promise.promisifyAll` instead of individual promise functions, so you can avoid using the context, so eg `var docClient = Promise.promisifyAll(new DOC.DynamoDB())`
2) don't use `const` for the table name, pass it as a stage variable (so it will be in request.env). 
3) no need to hard-code the region in Lambda, it will be picked up from the Lambda region itself anyway
4) instead of 

```
 return getItem(params)
        .then(function(data) {
            return data;
        });
```

just use `return getItem(params)` - it has the same effect

**Comment by gojko** [comment]
another improvement would be to add the dynamodb policy automatically. check out how [website email alert](https://github.com/claudiajs/example-projects/tree/master/website-email-alert) adds the SES policy (use the `--policies` arg when creating the lambda)

**Comment by marcusoftnet** [comment]
Absolutely brilliant feedback! Thanks a lot @gojko 

You made me (and my code) better

**Comment by gojko** [comment]
ok, one more iteration of this then:

```
    //  we could have read it below with request.post.userId etc.)
    var postedData = {
        userId: request.body.userId,
        name: request.body.name,
        age: request.body.age
    };

    // Set up parameters for dynamodb
    var params = {
        TableName: getTableName(request),
        Item: {
            userid: postedData.userId,
            name: postedData.name,
            age: postedData.age
        }
    };
```

why not just 

```
var params = {
    TableName: getTableName(request),
    Item: request.body
}
```

You seem to be copying body into postedData, then immediately copying it to Params, same keys and everything.

**Comment by gojko** [comment]
or if you'd like to keep postedData for documentation purpose, then at least

```
var postedData = {
    ... 
  }, params = {
    TableName: getTableName(request),
    Item: postedData
}
```

**Comment by marcusoftnet** [comment]
Yes, I had it for clarity and "white-listing" of fields, but you're right. 
Did it a little differently than suggest but it was an improvement. Thanks again

**Comment by gojko** [comment]
this looks very nice. thanks! I've added it and expanded the readme with sample CLI commands to create and configure the database.

**Pull request merged**
